# Generated by Django 3.2.7 on 2021-09-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='expriation_date',
            new_name='expiration_date',
        ),
    ]
