# Generated by Django 3.2.7 on 2021-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_expriation_date_link_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
