# Generated by Django 3.2.7 on 2021-09-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_template_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='completed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
