# Generated by Django 3.2.7 on 2021-09-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210923_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='username',
        ),
    ]
